name: Deploy

on:
  push:
    branches: [ api/prod ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - id: 'Checkout'
      uses: actions/checkout@v2
    - id: 'Auth'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/339690027814/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        service_account: 'github@battleword.iam.gserviceaccount.com'
    - name: 'Deploy'
      uses: 'google-github-actions/deploy-cloudrun@v0'
      with:
        source: '.'
        service: 'api'
        region: 'us-west1'